serverAddr = "us.gaianet.network"
serverPort = 7000
metadatas.deviceId = "device-9dcb799c6ef4d3bed7373f07"

[[proxies]]
name = "0x2dfcc84b5b980a9be84906d9942e446e51baf0d6.us.gaianet.network"
type = "http"
localPort = 8080
#remotePort = 80
subdomain = "0x2dfcc84b5b980a9be84906d9942e446e51baf0d6"
